// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertMockPlayerArgs {
    pub name: String,
}

impl From<InsertMockPlayerArgs> for super::Reducer {
    fn from(args: InsertMockPlayerArgs) -> Self {
        Self::InsertMockPlayer { name: args.name }
    }
}

impl __sdk::InModule for InsertMockPlayerArgs {
    type Module = super::RemoteModule;
}

pub struct InsertMockPlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_mock_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_mock_player {
    /// Request that the remote module invoke the reducer `insert_mock_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_insert_mock_player`] callbacks.
    fn insert_mock_player(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `insert_mock_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`InsertMockPlayerCallbackId`] can be passed to [`Self::remove_on_insert_mock_player`]
    /// to cancel the callback.
    fn on_insert_mock_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> InsertMockPlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_insert_mock_player`],
    /// causing it not to run in the future.
    fn remove_on_insert_mock_player(&self, callback: InsertMockPlayerCallbackId);
}

impl insert_mock_player for super::RemoteReducers {
    fn insert_mock_player(&self, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("insert_mock_player", InsertMockPlayerArgs { name })
    }
    fn on_insert_mock_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> InsertMockPlayerCallbackId {
        InsertMockPlayerCallbackId(self.imp.on_reducer(
            "insert_mock_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::InsertMockPlayer { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_insert_mock_player(&self, callback: InsertMockPlayerCallbackId) {
        self.imp.remove_on_reducer("insert_mock_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `insert_mock_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_insert_mock_player {
    /// Set the call-reducer flags for the reducer `insert_mock_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn insert_mock_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_insert_mock_player for super::SetReducerFlags {
    fn insert_mock_player(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("insert_mock_player", flags);
    }
}
